"""Turn a tuned parameter vector back into engine source constants.

Usage:
    python apply_params.py tuned_params.npy > new_constants.py

Paste the printed blocks over the corresponding definitions in your engine
file. `MG_TABLE`/`EG_TABLE` replace the two `for _pt in range(1, 7): ...`
loop's output directly (they're already the merged, value-baked tables the
engine expects) -- you can just assign them as literals and delete the
construction loop, or leave the loop and overwrite MG_TABLE/EG_TABLE after
it; either works since nothing else depends on MG_VALUE/PST separately.
"""

from __future__ import annotations

import sys

import numpy as np

import feature_extractor as fe


def fmt_table(vals) -> str:
    rows = []
    for r in range(8):
        row = vals[r * 8:(r + 1) * 8]
        rows.append("    " + ", ".join(f"{v:g}" for v in row) + ",")
    return "[\n" + "\n".join(rows) + "\n]"


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(f"usage: {sys.argv[0]} tuned_params.npy")

    params = np.load(sys.argv[1])
    mg, eg, tempo = fe.unpack(params)

    print("# ---- generated by apply_params.py, paste into the engine file ----\n")

    for pt, name in zip(range(1, 7), ["PAWN", "KNIGHT", "BISHOP", "ROOK", "QUEEN", "KING"]):
        mg_vals = mg[(pt - 1) * 64:pt * 64]
        eg_vals = eg[(pt - 1) * 64:pt * 64]
        print(f"# MG_TABLE[{pt}] / EG_TABLE[{pt}]  ({name})")
        print(f"MG_TABLE_{name} = {fmt_table(mg_vals)}")
        print(f"EG_TABLE_{name} = {fmt_table(eg_vals)}\n")

    print("# Rebuild MG_TABLE / EG_TABLE from the above:")
    print("MG_TABLE = [[0]*64, MG_TABLE_PAWN, MG_TABLE_KNIGHT, MG_TABLE_BISHOP, "
          "MG_TABLE_ROOK, MG_TABLE_QUEEN, MG_TABLE_KING]")
    print("EG_TABLE = [[0]*64, EG_TABLE_PAWN, EG_TABLE_KNIGHT, EG_TABLE_BISHOP, "
          "EG_TABLE_ROOK, EG_TABLE_QUEEN, EG_TABLE_KING]")
    print("# then: mg_table_np = np.array(MG_TABLE, dtype=np.int32)  (round first, see note below)")
    print()

    passed = mg[fe._PASSED_OFF:fe._PASSED_OFF + 8]
    passed_eg = eg[fe._PASSED_OFF:fe._PASSED_OFF + 8]
    print(f"PASSED_MG = {[round(v, 1) for v in passed]}")
    print(f"PASSED_EG = {[round(v, 1) for v in passed_eg]}")
    print(f"# new terms (not in the original constants -- add them to the eval):")
    print(f"SUPPORT_BONUS_MG = {mg[fe._SUPPORT_IDX]:.2f}")
    print(f"SUPPORT_BONUS_EG = {eg[fe._SUPPORT_IDX]:.2f}")
    print(f"BLOCKADE_PENALTY_MG = {mg[fe._BLOCKADE_IDX]:.2f}")
    print(f"BLOCKADE_PENALTY_EG = {eg[fe._BLOCKADE_IDX]:.2f}")
    print(f"# (these replace the //2 support halving and //{fe.BLOCKADE_DIVISOR} blockade")
    print(f"#  division in the shipped eval with additive bonus/penalty -- see README)")
    print()

    print(f"DOUBLED_MG, ISOLATED_MG = {mg[fe._DOUBLED_IDX]:.2f}, {mg[fe._ISOLATED_IDX]:.2f}")
    print(f"DOUBLED_EG, ISOLATED_EG = {eg[fe._DOUBLED_IDX]:.2f}, {eg[fe._ISOLATED_IDX]:.2f}")
    print(f"ROOK_OPEN_MG, ROOK_SEMI_MG = {mg[fe._ROOK_OPEN_IDX]:.2f}, {mg[fe._ROOK_SEMI_IDX]:.2f}")
    print(f"ROOK_OPEN_EG, ROOK_SEMI_EG = {eg[fe._ROOK_OPEN_IDX]:.2f}, {eg[fe._ROOK_SEMI_IDX]:.2f}")
    print(f"OUTPOST_MG, OUTPOST_EG = {mg[fe._OUTPOST_IDX]:.2f}, {eg[fe._OUTPOST_IDX]:.2f}")
    print(f"BISHOP_PAIR_MG, BISHOP_PAIR_EG = {mg[fe._BISHOP_PAIR_IDX]:.2f}, {eg[fe._BISHOP_PAIR_IDX]:.2f}")
    print(f"TEMPO = {tempo:.2f}  # replaces the hardcoded '+ 12' at the end of _evaluate_jit")
    print()
    print("# NOTE: _evaluate_jit does everything in int32. Round every value above")
    print("# with int(round(x)) before pasting it into actual table/constant literals.")


if __name__ == "__main__":
    main()
